apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: brokenroot
  namespace: argocd-test
spec:
  virtualhost:
    fqdn: example.com

  includes:              
    - name: child-service
      namespace: default
      conditions:
        - prefix: /svc
